### PR TITLE
Update maintainers.

### PR DESCRIPTION
**Pull request by artursouza**
Signed-off-by: Artur Souza <artursouza.ms@outlook.com>

### CODE REVIEW

**Review by halspang — CHANGES_REQUESTED** [review]
I should probably be on this list too as the .NET Maintainer :)

**Comment by artursouza** [comment]
> I should probably be on this list too as the .NET Maintainer :)

Thanks for reminding me.

**Review by halspang — APPROVED** [review]

**Review by yaron2 — APPROVED** [review]

**Comment by msfussell** [comment]
@artursouza Can you resubmit this PR, it needed changes. We need to change the companies for me, Yaron and Charlie.

**Comment by artursouza** [comment]
Yes. I will create a new one.

**Pull request merged**
