### PR TITLE
Add Dapr+Score+Humanitec blog post and presentations

### PR DESCRIPTION
**Pull request by mathieu-benoit**
- [Dapr with Score and Humanitec — Improving the Developer Experience of your Platform, on steroids!](https://medium.com/@mabenoit/dapr-with-score-and-humanitec-developer-experience-with-your-platform-on-steroids-a848f2de0a5a)
- [Dapr + Score + Humanitec demo](https://www.youtube.com/watch?v=4gT0Y6QxinU&t=140s)
- [Dapr + Score: Crafting and improving your developers experience](https://platformcon.com/talks/dapr-score-crafting-and-improving-your-developers-experience)

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Ready for your review, thanks!

**Review by marcduiker — APPROVED** [review]
LGTM

**Comment by marcduiker** [comment]
Thanks! @holopin-bot @mathieu-benoit writer-badge

**Comment by marcduiker** [comment]
And another one! @holopin-bot @mathieu-benoit presenter-badge

**Pull request merged**
