### PR TITLE
added community call instances through March 2022

### PR DESCRIPTION
**Pull request by willtsai**
added community call instances through March 2022, reverting back to 10am PST schedule.

### CODE REVIEW

**Comment by willtsai** [comment]
Open question: should we skip 11/30 and 12/28 occurrences due to holidays?

**Comment by yaron2** [comment]
> Open question: should we skip 11/30 and 12/28 occurrences due to holidays?

Unless it falls on an actual holiday than no. Traditionally we've always held a single meeting in December, so 12/28 can be cancelled IMO.

**Comment by yaron2** [comment]
Based on what are you cancelling the Asia friendly times? I do not remember seeing STC decision about this. This PR cannot be merged as is.

**Comment by willtsai** [comment]
> Based on what are you cancelling the Asia friendly times? I do not remember seeing STC decision about this. This PR cannot be merged as is.

yes, I will be reverting back to include the Asia friendly times until we have guidance from the STC. sorry for the confusion.

**Comment by willtsai** [comment]
made revisions to add back Asia-friendly alternating occurrences and removed Dec 28 occurrence.

**Review by msfussell — APPROVED** [review]
LGTM

**Pull request merged**
