### PR TITLE
Added a blog and a conference session by Eduard Keilholz

### PR DESCRIPTION
**Pull request by nikneem**

### CODE REVIEW

**Comment by marcduiker** [comment]
@nikneem can you add a sign-off to your commit as is mentioned here: https://docs.dapr.io/contributing/contributing-overview/#i-didnt-sign-my-commit-now-what

**Comment by nikneem** [comment]
Hope it works ;)

**Comment by marcduiker** [comment]
@holopin-bot @nikneem presenter-badge

**Comment by marcduiker** [comment]
@holopin-bot @nikneem writer-badge

**Comment by marcduiker** [comment]
@holopin-bot @fvandillen presenter-badge

**Pull request merged**
